In [64]:
import pandas as pd
import numpy as np
from datetime import datetime
import time

In [1]:
import os
os.chdir("../raw data")

In [65]:
# importing fips data. and rearranging the columns
fips = pd.read_excel("fips.xlsx")
fips = fips.iloc[:, [1, 3, 2, 4, 5]]

# Convert the 'integers' to integers in fips file.
for i in range(fips.shape[0]):
    if fips.iloc[i, 4] != 'unknown':
        fips.iloc[i, 4] = int(fips.iloc[i, 4])
        fips.iloc[i, 2] = int(fips.iloc[i, 2])

In [66]:
# importing the census data

pop = pd.read_excel("US_county_Pop.xlsx")

In [67]:
years = [str(item) for item in range(2010,2019)]
params = pop.iloc[:, 6:].columns

col_names = []
for year in years:
    for param in params:
        col_names.append(year + "_" + param)

for col in col_names:
    fips[col] = ""

In [68]:
pop.head()

,stname,stfips,ctyname,ctyfips,fips,year,tot,ageg1,ageg2,ageg3,...,ageg16,ageg17,ageg18,male,Hispanic,nH_White,nH_Black,nH_Indian_Na,nH_Asian,nH_Hawaii_Na
0,Alabama,1,Autauga County,1,1001,2010,54754,0.065292,0.072287,0.078332,...,0.023030,0.013588,0.010191,0.487088,0.023889,0.772272,0.176499,0.004036,0.008931,0.000420
1,Alabama,1,Autauga County,1,1001,2011,55208,0.064302,0.070624,0.078159,...,0.023801,0.014201,0.010922,0.488661,0.024236,0.770396,0.177601,0.004148,0.009147,0.000598
2,Alabama,1,Autauga County,1,1001,2012,54936,0.061872,0.068971,0.079292,...,0.024774,0.015218,0.011541,0.488168,0.023973,0.767657,0.179718,0.004460,0.009902,0.000528
3,Alabama,1,Autauga County,1,1001,2013,54713,0.058761,0.068576,0.076691,...,0.026063,0.016322,0.011661,0.485735,0.024912,0.763987,0.180579,0.004569,0.010034,0.000603
4,Alabama,1,Autauga County,1,1001,2014,54876,0.058076,0.067662,0.075607,...,0.026933,0.017239,0.012191,0.488082,0.026059,0.760806,0.181865,0.004519,0.010332,0.000656

In [69]:
fips.head()
# pop.head()

,stname,stfips,ctyname,ctyfips,fips,year,tot,ageg1,ageg2,ageg3,...,ageg16,ageg17,ageg18,male,Hispanic,nH_White,nH_Black,nH_Indian_Na,nH_Asian,nH_Hawaii_Na
0,Alabama,1,Autauga County,1,1001,2010,54754,0.065292,0.072287,0.078332,...,0.023030,0.013588,0.010191,0.487088,0.023889,0.772272,0.176499,0.004036,0.008931,0.000420
1,Alabama,1,Autauga County,1,1001,2011,55208,0.064302,0.070624,0.078159,...,0.023801,0.014201,0.010922,0.488661,0.024236,0.770396,0.177601,0.004148,0.009147,0.000598
2,Alabama,1,Autauga County,1,1001,2012,54936,0.061872,0.068971,0.079292,...,0.024774,0.015218,0.011541,0.488168,0.023973,0.767657,0.179718,0.004460,0.009902,0.000528
3,Alabama,1,Autauga County,1,1001,2013,54713,0.058761,0.068576,0.076691,...,0.026063,0.016322,0.011661,0.485735,0.024912,0.763987,0.180579,0.004569,0.010034,0.000603
4,Alabama,1,Autauga County,1,1001,2014,54876,0.058076,0.067662,0.075607,...,0.026933,0.017239,0.012191,0.488082,0.026059,0.760806,0.181865,0.004519,0.010332,0.000656

In [70]:
def row_loc_county(inp):
    location = fips.index[(fips['fips']) == inp].values
    location = location.tolist()
    return location

In [80]:
for i in range(pop.shape[0]):
    for item in pop.columns[6:]:
        fips.iloc[row_loc_county(pop.iloc[i, 4]), fips.columns.get_loc(str(pop.iloc[i, 5]) + "_" + item)] = pop.iloc[i, pop.columns.get_loc(item)]

In [2]:
os.chdir("../data")

In [82]:
fips.to_csv("census_pop.csv")