# A python code to make the dictionary

In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
base = pd.read_csv("base dictionary.csv", engine='python')
base

,variable name,label,source,file
0,Unnamed: 0,Row number,NaN,casesAndDeaths.csv
1,stfips,State name,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv
2,stname,State FIPS code,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv
3,ctyfips,County name,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv
4,ctyname,County FIPS code,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv
...,...,...,...,...
213,moderna_receive_dose1_dose2_simultaneously_yyy...,Moderna: receive dose 1 and dose 2 simultaneously,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv
214,moderna_sovereign_nation_supplement_yyyymmdd,Moderna: Sovereign Nation Supplement Project,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv
215,janssen_allocation_dose1_yyyymmdd,Janssen: weekly allocation dose 1,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv
216,janssen_receive_dose1_dose2_simultaneously,Janssen: receive dose 1 and dose 2 simultaneously,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv
217,janssen_sovereign_nation_supplement,Janssen: Sovereign Nation Supplement Project,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv

# Dictionary for cases and deaths

In [3]:
base_cd = base.loc[base["file"] == "casesAndDeaths.csv"]
base_cd

,variable name,label,source,file
0,Unnamed: 0,Row number,NaN,casesAndDeaths.csv
1,stfips,State name,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv
2,stname,State FIPS code,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv
3,ctyfips,County name,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv
4,ctyname,County FIPS code,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv
5,fips,FIPS code of state-county,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv
6,confirmed_cases_yyyymmdd,No of confirmed cases on yyyymmdd,https://github.com/CSSEGISandData/COVID-19,casesAndDeaths.csv
7,deaths_yyyymmdd,No of deaths on yyyymmdd,https://github.com/CSSEGISandData/COVID-19,casesAndDeaths.csv

In [4]:
dict = {"variable name":[] , "start column": [], "end column":[], "start date":[], "end date": []}
dictionary = pd.DataFrame(dict)
dictionary

df = pd.read_csv("../Pandemic/casesAndDeaths.csv")
name = []
start = []
end = []

start_date = []
end_date = []

file = []

ct = 0

for col in df.columns:
    if col.split("_")[:-1] == []:
        name.append(col)
        start.append(df.columns.get_loc(col))
        start_date.append("")
        file.append("casesAndDeaths.csv")
        if ct != 0:
            end.append(df.columns.get_loc(col) -1) 
            end_date.append("")
    else:       
        new = ("_".join(col.split("_")[:-1])) + "_yyyymmdd"
        
        if new not in name:
            name.append(new)
            start.append(df.columns.get_loc(col))
            start_date.append(col.split("_")[-1])
            file.append("casesAndDeaths.csv")
            if ct != 0:
                end.append(df.columns.get_loc(col) -1) 
                end_date.append(df.columns[df.columns.get_loc(col) -1].split("_")[-1])
    ct = ct+1

end.append(len(df.columns) -1)
end_date.append(df.columns[-1].split("_")[-1])

dictionary["variable name"] = name
dictionary["start column"] = start
dictionary["end column"] = end
dictionary["start date"] = start_date
dictionary["end date"] = end_date

for i in range(dictionary.shape[0]):
    if isinstance(dictionary.iloc[i, 3], str) == True:
        if dictionary.iloc[i, 3].isnumeric() == False:
            dictionary.iloc[i, 3] = ""
    if isinstance(dictionary.iloc[i, 4], str) == True:
        if dictionary.iloc[i, 4].isnumeric() == False:
            dictionary.iloc[i, 4] = ""
dictionary_casesAndDeaths = dictionary
dictionary_casesAndDeaths

              variable name  start column  end column start date  end date
0                Unnamed: 0             0           0
1                    stfips             1           1
2                    stname             2           2
3                   ctyfips             3           3
4                   ctyname             4           4
5                      fips             5           5
6  confirmed_cases_yyyymmdd             6         420   20200122  20210311
7           deaths_yyyymmdd           421         835   20200122  20210311

In [5]:
dictionary_casesAndDeaths = pd.merge(base_cd, dictionary, on="variable name")
dictionary_casesAndDeaths

,variable name,label,source,file,start column,end column,start date,end date
0,Unnamed: 0,Row number,NaN,casesAndDeaths.csv,0,0,,
1,stfips,State name,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv,1,1,,
2,stname,State FIPS code,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv,2,2,,
3,ctyfips,County name,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv,3,3,,
4,ctyname,County FIPS code,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv,4,4,,
5,fips,FIPS code of state-county,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv,5,5,,
6,confirmed_cases_yyyymmdd,No of confirmed cases on yyyymmdd,https://github.com/CSSEGISandData/COVID-19,casesAndDeaths.csv,6,420,20200122,20210311
7,deaths_yyyymmdd,No of deaths on yyyymmdd,https://github.com/CSSEGISandData/COVID-19,casesAndDeaths.csv,421,835,20200122,20210311

# Dictionary for mobility data

In [6]:
base_mob = base.loc[base["file"].isin(['mobility_google.csv', 'mobility_unacast.csv', 'mobility_descartes.csv'])]
base_mob

,variable name,label,source,file
14,grocery_yyyymmdd,% increase in grocery stores area,https://www.google.com/covid19/mobility/,mobility_google.csv
15,parks_yyyymmdd,% increase in parks stores area,https://www.google.com/covid19/mobility/,mobility_google.csv
16,residential_yyyymmdd,% increase in residential stores area,https://www.google.com/covid19/mobility/,mobility_google.csv
17,retail_yyyymmdd,% increase in retail stores area,https://www.google.com/covid19/mobility/,mobility_google.csv
18,transit_yyyymmdd,% increase in transit stores area,https://www.google.com/covid19/mobility/,mobility_google.csv
19,workplace_yyyymmdd,% increase in workplace stores area,https://www.google.com/covid19/mobility/,mobility_google.csv
20,county_population_yyyymmdd,The total count of the population for this seg...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
21,covid_yyyymmdd,Identifiers whether event date is PRE or POST ...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
22,daily_distance_diff_yyyymmdd,Change of average distance traveled from basel...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
23,daily_visitation_diff_yyyymmdd,Change of visits to non-essential retail and s...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
24,encounters_rate_yyyymmdd,Rate of unique human encounters per KmÂ² relati...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
25,grade_distance_yyyymmdd,"A, B, C, D or F score describing county's redu...",https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
26,grade_encounters_yyyymmdd,"A, B, C, D, or F score describing rate of enco...",https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
27,grade_total_yyyymmdd,"A, A-, B, B-, C, C-, D, D- or F score describi...",https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
28,grade_visitation_yyyymmdd,"A, B, C, D or F score describing county's redu...",https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
29,last_updated_yyyymmdd,Timestamp of when this data was processed and ...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
30,n_grade_distance_yyyymmdd,Corresponding number for letter grade where A ...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
31,n_grade_encounters_yyyymmdd,Corresponding number for letter grade where A=...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
32,n_grade_total_yyyymmdd,Corresponding number for letter grade where A ...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
33,n_grade_visitation_yyyymmdd,Corresponding number for letter grade where A ...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
34,weekday_yyyymmdd,Weekday,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv
35,m50_yyyymmdd,The median of the max-distance mobility for al...,https://github.com/descarteslabs/DL-COVID-19,mobility_descartes.csv
36,m50_index_yyyymmdd,"The percent of normal m50 in the region, with ...",https://github.com/descarteslabs/DL-COVID-19,mobility_descartes.csv
37,samples_yyyymmdd,The number of samples observed in the specifie...,https://github.com/descarteslabs/DL-COVID-19,mobility_descartes.csv

In [7]:
d = {'variable name':[] , 'start column': [], 'end column':[], 'start date':[], 'end date': []}

for item in ["mobility_google.csv", "mobility_unacast.csv", "mobility_descartes.csv"]:
    df = pd.read_csv("../Pandemic/" + item)
    temp_base = base_mob[base_mob['file'] == item].copy().reset_index(drop = True)
    for i in range(temp_base.shape[0]):
        d['variable name'].append(temp_base.loc[i, 'variable name'])
        temp_var = temp_base.loc[i, 'variable name'].replace('_yyyymmdd', '')
        temp_id = [i for i, s in enumerate(df.columns) if temp_var in s]
        temp_date = [re.findall('20[\d]+', x)[0] for x in df.columns[temp_id]]
        if len(temp_id) > 0:
            d['start column'].append(temp_id[0])
            d['end column'].append(temp_id[-1])
            d['start date'].append(temp_date[0])
            d['end date'].append(temp_date[-1])
        else:
            d['start column'].append(-1)
            d['end column'].append(-1)
            d['start date'].append(-1)
            d['end date'].append(-1)
        
dictionary_mobility = pd.DataFrame(d)
dictionary_mobility

,variable name,start column,end column,start date,end date
0,grocery_yyyymmdd,6,387,20200215,20210302
1,parks_yyyymmdd,388,1151,20200215,20210302
2,residential_yyyymmdd,1152,1915,20200215,20210302
3,retail_yyyymmdd,-1,-1,-1,-1
4,transit_yyyymmdd,1916,2297,20200215,20210302
5,workplace_yyyymmdd,2298,3061,20200215,20210302
6,county_population_yyyymmdd,6,6,2018,2018
7,covid_yyyymmdd,7,96,20200224,20200523
8,daily_distance_diff_yyyymmdd,97,186,20200224,20200523
9,daily_visitation_diff_yyyymmdd,187,276,20200224,20200523
10,encounters_rate_yyyymmdd,277,366,20200224,20200523
11,grade_distance_yyyymmdd,367,906,20200224,20200523
12,grade_encounters_yyyymmdd,457,996,20200224,20200523
13,grade_total_yyyymmdd,547,1086,20200224,20200523
14,grade_visitation_yyyymmdd,637,1176,20200224,20200523
15,last_updated_yyyymmdd,727,816,20200224,20200523
16,n_grade_distance_yyyymmdd,817,906,20200224,20200523
17,n_grade_encounters_yyyymmdd,907,996,20200224,20200523
18,n_grade_total_yyyymmdd,997,1086,20200224,20200523
19,n_grade_visitation_yyyymmdd,1087,1176,20200224,20200523
20,weekday_yyyymmdd,1177,1266,20200224,20200523
21,m50_yyyymmdd,6,705,20200301,20210303
22,m50_index_yyyymmdd,356,705,20200301,20210303
23,samples_yyyymmdd,706,1055,20200301,20210303

In [8]:
# remove the deleted variable in the original data
dictionary_mobility = dictionary_mobility.drop(dictionary_mobility[dictionary_mobility['start column']==-1].index,
                                              axis = 0)
dictionary_mobility

,variable name,start column,end column,start date,end date
0,grocery_yyyymmdd,6,387,20200215,20210302
1,parks_yyyymmdd,388,1151,20200215,20210302
2,residential_yyyymmdd,1152,1915,20200215,20210302
4,transit_yyyymmdd,1916,2297,20200215,20210302
5,workplace_yyyymmdd,2298,3061,20200215,20210302
6,county_population_yyyymmdd,6,6,2018,2018
7,covid_yyyymmdd,7,96,20200224,20200523
8,daily_distance_diff_yyyymmdd,97,186,20200224,20200523
9,daily_visitation_diff_yyyymmdd,187,276,20200224,20200523
10,encounters_rate_yyyymmdd,277,366,20200224,20200523
11,grade_distance_yyyymmdd,367,906,20200224,20200523
12,grade_encounters_yyyymmdd,457,996,20200224,20200523
13,grade_total_yyyymmdd,547,1086,20200224,20200523
14,grade_visitation_yyyymmdd,637,1176,20200224,20200523
15,last_updated_yyyymmdd,727,816,20200224,20200523
16,n_grade_distance_yyyymmdd,817,906,20200224,20200523
17,n_grade_encounters_yyyymmdd,907,996,20200224,20200523
18,n_grade_total_yyyymmdd,997,1086,20200224,20200523
19,n_grade_visitation_yyyymmdd,1087,1176,20200224,20200523
20,weekday_yyyymmdd,1177,1266,20200224,20200523
21,m50_yyyymmdd,6,705,20200301,20210303
22,m50_index_yyyymmdd,356,705,20200301,20210303
23,samples_yyyymmdd,706,1055,20200301,20210303

In [9]:
dictionary_mobility = pd.merge(base_mob, dictionary_mobility, on="variable name")
dictionary_mobility

,variable name,label,source,file,start column,end column,start date,end date
0,grocery_yyyymmdd,% increase in grocery stores area,https://www.google.com/covid19/mobility/,mobility_google.csv,6,387,20200215,20210302
1,parks_yyyymmdd,% increase in parks stores area,https://www.google.com/covid19/mobility/,mobility_google.csv,388,1151,20200215,20210302
2,residential_yyyymmdd,% increase in residential stores area,https://www.google.com/covid19/mobility/,mobility_google.csv,1152,1915,20200215,20210302
3,transit_yyyymmdd,% increase in transit stores area,https://www.google.com/covid19/mobility/,mobility_google.csv,1916,2297,20200215,20210302
4,workplace_yyyymmdd,% increase in workplace stores area,https://www.google.com/covid19/mobility/,mobility_google.csv,2298,3061,20200215,20210302
5,county_population_yyyymmdd,The total count of the population for this seg...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,6,6,2018,2018
6,covid_yyyymmdd,Identifiers whether event date is PRE or POST ...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,7,96,20200224,20200523
7,daily_distance_diff_yyyymmdd,Change of average distance traveled from basel...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,97,186,20200224,20200523
8,daily_visitation_diff_yyyymmdd,Change of visits to non-essential retail and s...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,187,276,20200224,20200523
9,encounters_rate_yyyymmdd,Rate of unique human encounters per KmÂ² relati...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,277,366,20200224,20200523
10,grade_distance_yyyymmdd,"A, B, C, D or F score describing county's redu...",https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,367,906,20200224,20200523
11,grade_encounters_yyyymmdd,"A, B, C, D, or F score describing rate of enco...",https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,457,996,20200224,20200523
12,grade_total_yyyymmdd,"A, A-, B, B-, C, C-, D, D- or F score describi...",https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,547,1086,20200224,20200523
13,grade_visitation_yyyymmdd,"A, B, C, D or F score describing county's redu...",https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,637,1176,20200224,20200523
14,last_updated_yyyymmdd,Timestamp of when this data was processed and ...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,727,816,20200224,20200523
15,n_grade_distance_yyyymmdd,Corresponding number for letter grade where A ...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,817,906,20200224,20200523
16,n_grade_encounters_yyyymmdd,Corresponding number for letter grade where A=...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,907,996,20200224,20200523
17,n_grade_total_yyyymmdd,Corresponding number for letter grade where A ...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,997,1086,20200224,20200523
18,n_grade_visitation_yyyymmdd,Corresponding number for letter grade where A ...,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,1087,1176,20200224,20200523
19,weekday_yyyymmdd,Weekday,https://www.unacast.com/covid19/social-distanc...,mobility_unacast.csv,1177,1266,20200224,20200523
20,m50_yyyymmdd,The median of the max-distance mobility for al...,https://github.com/descarteslabs/DL-COVID-19,mobility_descartes.csv,6,705,20200301,20210303
21,m50_index_yyyymmdd,"The percent of normal m50 in the region, with ...",https://github.com/descarteslabs/DL-COVID-19,mobility_descartes.csv,356,705,20200301,20210303
22,samples_yyyymmdd,The number of samples observed in the specifie...,https://github.com/descarteslabs/DL-COVID-19,mobility_descartes.csv,706,1055,20200301,20210303

# Dictionary for medical data
This needs to be fixed next week [Note on 3/8/2021]

In [10]:
base_med = base.loc[base["file"].isin(['medical_covidtracking.csv', 'medical_govex.csv'])]
base_med

,variable name,label,source,file
44,FatalityRa,Fatality rate,https://coronavirus.jhu.edu/us-map,medical_govex.csv
45,Confirmedb,Not sure,https://coronavirus.jhu.edu/us-map,medical_govex.csv
46,DeathsbyPo,Not sure,https://coronavirus.jhu.edu/us-map,medical_govex.csv
47,PCTPOVALL_,Not sure,https://coronavirus.jhu.edu/us-map,medical_govex.csv
48,Unemployme,Unemployment rate,https://coronavirus.jhu.edu/us-map,medical_govex.csv
...,...,...,...,...
127,positiveIncrease_yyyymmdd,Increase in positive cases on that day,https://covidtracking.com/api,medical_covidtracking.csv
128,recovered_yyyymmdd,People who have recovered,https://covidtracking.com/api,medical_covidtracking.csv
129,total_yyyymmdd,DEPRECATED Will be removed in the future. (pos...,https://covidtracking.com/api,medical_covidtracking.csv
130,totalTestResults_yyyymmdd,Calculated value (positive + negative) of tota...,https://covidtracking.com/api,medical_covidtracking.csv
131,totalTestResultsIncrease_yyyymmdd,Total increase in number of test results on th...,https://covidtracking.com/api,medical_covidtracking.csv

In [15]:
d = {'variable name':[] , 'start column': [], 'end column':[], 'start date':[], 'end date': []}

for item in ['medical_covidtracking.csv', 'medical_govex.csv']:
    df = pd.read_csv("../Pandemic/" + item)
    temp_base = base_med[base_med['file'] == item].copy().reset_index(drop = True)
    for i in range(temp_base.shape[0]):
        d['variable name'].append(temp_base.loc[i, 'variable name'])
        temp_var = temp_base.loc[i, 'variable name'].replace('_yyyymmdd', '')
        temp_id = [i for i, s in enumerate(df.columns) if temp_var in s]
        temp_date = [re.findall('20[\d]+', x) for x in df.columns[temp_id]]
        if len(temp_date[0]) != 0:
            temp_date = [x[0] for x in temp_date]
        else:
            temp_date = [-1]
        if len(temp_id) > 0:
            d['start column'].append(temp_id[0])
            d['end column'].append(temp_id[-1])
            d['start date'].append(temp_date[0])
            d['end date'].append(temp_date[-1])
        else:
            d['start column'].append(-1)
            d['end column'].append(-1)
            d['start date'].append(-1)
            d['end date'].append(-1)
        
dictionary_medical = pd.DataFrame(d)
dictionary_medical

                variable name  start column  end column start date  end date
0   dataQualityGrade_yyyymmdd         18063       18482   20200113  20210307
1        dateChecked_yyyymmdd          7983        8402   20200113  20210307
2              death_yyyymmdd          6723       18902   20200113  20210307
3      deathIncrease_yyyymmdd         18483       18902   20200113  20210307
4               hash_yyyymmdd         19323       19742   20200113  20210307
..                        ...           ...         ...        ...       ...
83                    NonHisp            44          65         -1        -1
84                  Age_35_64            66          66         -1        -1
85                  Age_65_74            67          67         -1        -1
86                Shape__Area            91          91         -1        -1
87              Shape__Length            92          92         -1        -1

[88 rows x 5 columns]

In [17]:
dictionary_medical = pd.merge(base_med, dictionary_medical, on="variable name", how='outer')
dictionary_medical.to_csv("med_dict_temp.csv")
dictionary_medical

,variable name,label,source,file,start column,end column,start date,end date
0,FatalityRa,Fatality rate,https://coronavirus.jhu.edu/us-map,medical_govex.csv,6,6,-1,-1
1,Confirmedb,Not sure,https://coronavirus.jhu.edu/us-map,medical_govex.csv,7,7,-1,-1
2,DeathsbyPo,Not sure,https://coronavirus.jhu.edu/us-map,medical_govex.csv,8,8,-1,-1
3,PCTPOVALL_,Not sure,https://coronavirus.jhu.edu/us-map,medical_govex.csv,9,9,-1,-1
4,Unemployme,Unemployment rate,https://coronavirus.jhu.edu/us-map,medical_govex.csv,10,10,-1,-1
...,...,...,...,...,...,...,...,...
83,positiveIncrease_yyyymmdd,Increase in positive cases on that day,https://covidtracking.com/api,medical_covidtracking.csv,15963,16382,20200113,20210307
84,recovered_yyyymmdd,People who have recovered,https://covidtracking.com/api,medical_covidtracking.csv,5043,5462,20200113,20210307
85,total_yyyymmdd,DEPRECATED Will be removed in the future. (pos...,https://covidtracking.com/api,medical_covidtracking.csv,1683,17642,20200113,20210307
86,totalTestResults_yyyymmdd,Calculated value (positive + negative) of tota...,https://covidtracking.com/api,medical_covidtracking.csv,1683,17642,20200113,20210307
87,totalTestResultsIncrease_yyyymmdd,Total increase in number of test results on th...,https://covidtracking.com/api,medical_covidtracking.csv,17223,17642,20200113,20210307

# Dictionary for policy data

In [18]:
base_policy = base.loc[base["file"] == "policy.csv"]
base_policy

,variable name,label,source,file
132,Unnamed: 0,Row number,NaN,policy.csv
133,stfips,State name,https://www.census.gov/geographies/reference-f...,policy.csv
134,stname,State FIPS code,https://www.census.gov/geographies/reference-f...,policy.csv
135,ctyfips,County name,https://www.census.gov/geographies/reference-f...,policy.csv
136,ctyname,County FIPS code,https://www.census.gov/geographies/reference-f...,policy.csv
...,...,...,...,...
200,Proof of work eligibility requirement for vacc...,Proof of work eligibility requirement for vacc...,https://www.bu.edu/sph/news/articles/2020/trac...,policy.csv
201,Proof of age eligibility requirement for vacci...,Proof of age eligibility requirement for vacci...,https://www.bu.edu/sph/news/articles/2020/trac...,policy.csv
202,Proof of residency requirement for vaccination,Proof of residency requirement for vaccination,https://www.bu.edu/sph/news/articles/2020/trac...,policy.csv
203,Penalty for failure to comply with vaccine dis...,Penalty for failure to comply with vaccine dis...,https://www.bu.edu/sph/news/articles/2020/trac...,policy.csv
204,Expanded scope of practice of certain health p...,Expanded scope of practice of certain health p...,https://www.bu.edu/sph/news/articles/2020/trac...,policy.csv

In [19]:
dict = {"variable name":[] , "start column": [], "end column":[], "start date":[], "end date": []}
dictionary = pd.DataFrame(dict)
dictionary

df = pd.read_csv("../Pandemic/policy.csv")
name = []
start = []
end = []

start_date = []
end_date = []

file = []

ct = 0

for col in df.columns:
    if col.split("_")[:-1] == []:
        name.append(col)
        start.append(df.columns.get_loc(col))
        start_date.append("")
        file.append("policy.csv")
        if ct != 0:
            end.append(df.columns.get_loc(col) -1) 
            end_date.append("")
    else:       
        new = ("_".join(col.split("_")[:-1])) + "_yyyymmdd"
        
        if new not in name:
            name.append(new)
            start.append(df.columns.get_loc(col))
            start_date.append(col.split("_")[-1])
            file.append("policy.csv")
            if ct != 0:
                end.append(df.columns.get_loc(col) -1) 
                end_date.append(df.columns[df.columns.get_loc(col) -1].split("_")[-1])
    ct = ct+1

end.append(len(df.columns) -1)
end_date.append(df.columns[-1].split("_")[-1])

dictionary["variable name"] = name
dictionary["start column"] = start
dictionary["end column"] = end
dictionary["start date"] = start_date
dictionary["end date"] = end_date

for i in range(dictionary.shape[0]):
    if isinstance(dictionary.iloc[i, 3], str) == True:
        if dictionary.iloc[i, 3].isnumeric() == False:
            dictionary.iloc[i, 3] = ""
    if isinstance(dictionary.iloc[i, 4], str) == True:
        if dictionary.iloc[i, 4].isnumeric() == False:
            dictionary.iloc[i, 4] = ""


dictionary_policy = dictionary
dictionary_policy

                   variable name  start column  end column start date end date
0                     Unnamed: 0             0           0
1                         stfips             1           1
2                         stname             2           2
3                        ctyfips             3           3
4                        ctyname             4           4
..                           ...           ...         ...        ...      ...
211  [Planned] 2022 Minimum Wage           211         211
212  [Planned] 2023 Minimum Wage           212         212
213  [Planned] 2024 Minimum Wage           213         213
214  [Planned] 2025 Minimum Wage           214         214
215  [Planned] 2026 Minimum Wage           215         215

[216 rows x 5 columns]

In [20]:
dictionary_policy = pd.merge(base_policy, dictionary_policy, on="variable name")
dictionary_policy

,variable name,label,source,file,start column,end column,start date,end date
0,Unnamed: 0,Row number,NaN,policy.csv,0,0,,
1,stfips,State name,https://www.census.gov/geographies/reference-f...,policy.csv,1,1,,
2,stname,State FIPS code,https://www.census.gov/geographies/reference-f...,policy.csv,2,2,,
3,ctyfips,County name,https://www.census.gov/geographies/reference-f...,policy.csv,3,3,,
4,ctyname,County FIPS code,https://www.census.gov/geographies/reference-f...,policy.csv,4,4,,
...,...,...,...,...,...,...,...,...
62,Proof of work eligibility requirement for vacc...,Proof of work eligibility requirement for vacc...,https://www.bu.edu/sph/news/articles/2020/trac...,policy.csv,87,87,,
63,Proof of age eligibility requirement for vacci...,Proof of age eligibility requirement for vacci...,https://www.bu.edu/sph/news/articles/2020/trac...,policy.csv,88,88,,
64,Proof of residency requirement for vaccination,Proof of residency requirement for vaccination,https://www.bu.edu/sph/news/articles/2020/trac...,policy.csv,89,89,,
65,Penalty for failure to comply with vaccine dis...,Penalty for failure to comply with vaccine dis...,https://www.bu.edu/sph/news/articles/2020/trac...,policy.csv,90,90,,
66,Expanded scope of practice of certain health p...,Expanded scope of practice of certain health p...,https://www.bu.edu/sph/news/articles/2020/trac...,policy.csv,91,91,,

# Dictionary for vaccine data

In [21]:
base_vaccine = base.loc[base["file"] == "vaccine_allocation.csv"]
base_vaccine

,variable name,label,source,file
205,jurisdiction,Jurisdiction,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv
206,no_pfizer_because_ultra_cold_requirement_yyyymmdd,No pfizer because ultra-cold requirement,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv
207,pfizer_allocation_dose1_yyyymmdd,Pfizer: weekly allocation of dose 1,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv
208,pfizer_allocation_dose2_yyyymmdd,Pfizer: weekly allocation of dose 2,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv
209,pfizer_receive_dose1_dose2_simultaneously_yyyy...,Pfizer: receive dose 1 and dose 2 simultaneously,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv
210,pfizer_sovereign_nation_supplement_yyyymmdd,Pfizer: Sovereign Nation Supplement Project,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv
211,moderna_allocation_dose1_yyyymmdd,Moderna: weekly allocation of dose 1,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv
212,moderna_allocation_dose2_yyyymmdd,Moderna: weekly allocation of dose 2,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv
213,moderna_receive_dose1_dose2_simultaneously_yyy...,Moderna: receive dose 1 and dose 2 simultaneously,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv
214,moderna_sovereign_nation_supplement_yyyymmdd,Moderna: Sovereign Nation Supplement Project,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv
215,janssen_allocation_dose1_yyyymmdd,Janssen: weekly allocation dose 1,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv
216,janssen_receive_dose1_dose2_simultaneously,Janssen: receive dose 1 and dose 2 simultaneously,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv
217,janssen_sovereign_nation_supplement,Janssen: Sovereign Nation Supplement Project,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv

In [22]:
df = pd.read_csv("../Pandemic/vaccine_allocation.csv")

d = {'variable name':[] , 'start column': [], 'end column':[], 'start date':[], 'end date': []}

temp_base = base_vaccine.copy().reset_index(drop = True)
for i in range(temp_base.shape[0]):
    d['variable name'].append(temp_base.loc[i, 'variable name'])
    temp_var = temp_base.loc[i, 'variable name'].replace('_yyyymmdd', '')
    temp_id = [i for i, s in enumerate(df.columns) if temp_var in s]
    if temp_var != 'jurisdiction':
        temp_date = [re.findall('20[\d]+', x)[0] for x in df.columns[temp_id]]
    if len(temp_id) > 1:
        d['start column'].append(temp_id[0])
        d['end column'].append(temp_id[-1])
        d['start date'].append(temp_date[0])
        d['end date'].append(temp_date[-1])
    else:
        if len(temp_id) == 1:
            d['start column'].append(temp_id[0])
            d['end column'].append(temp_id[0])
        else:
            d['start column'].append(-1)
            d['end column'].append(-1)
        d['start date'].append(-1)
        d['end date'].append(-1)

dictionary_vaccine = pd.DataFrame(d)
dictionary_vaccine

,variable name,start column,end column,start date,end date
0,jurisdiction,0,0,-1,-1
1,no_pfizer_because_ultra_cold_requirement_yyyymmdd,1,14,20201214,20210315
2,pfizer_allocation_dose1_yyyymmdd,15,28,20201214,20210315
3,pfizer_allocation_dose2_yyyymmdd,29,42,20201214,20210315
4,pfizer_receive_dose1_dose2_simultaneously_yyyy...,43,56,20201214,20210315
5,pfizer_sovereign_nation_supplement_yyyymmdd,57,70,20201214,20210315
6,moderna_allocation_dose1_yyyymmdd,71,83,20201221,20210315
7,moderna_allocation_dose2_yyyymmdd,84,96,20201221,20210315
8,moderna_receive_dose1_dose2_simultaneously_yyy...,97,109,20201221,20210315
9,moderna_sovereign_nation_supplement_yyyymmdd,110,122,20201221,20210315
10,janssen_allocation_dose1_yyyymmdd,123,124,20210301,20210315
11,janssen_receive_dose1_dose2_simultaneously,125,126,20210301,20210315
12,janssen_sovereign_nation_supplement,127,128,20210301,20210315

In [23]:
dictionary_vaccine = pd.merge(base_vaccine, dictionary_vaccine, on="variable name")
dictionary_vaccine

,variable name,label,source,file,start column,end column,start date,end date
0,jurisdiction,Jurisdiction,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv,0,0,-1,-1
1,no_pfizer_because_ultra_cold_requirement_yyyymmdd,No pfizer because ultra-cold requirement,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv,1,14,20201214,20210315
2,pfizer_allocation_dose1_yyyymmdd,Pfizer: weekly allocation of dose 1,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv,15,28,20201214,20210315
3,pfizer_allocation_dose2_yyyymmdd,Pfizer: weekly allocation of dose 2,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv,29,42,20201214,20210315
4,pfizer_receive_dose1_dose2_simultaneously_yyyy...,Pfizer: receive dose 1 and dose 2 simultaneously,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv,43,56,20201214,20210315
5,pfizer_sovereign_nation_supplement_yyyymmdd,Pfizer: Sovereign Nation Supplement Project,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv,57,70,20201214,20210315
6,moderna_allocation_dose1_yyyymmdd,Moderna: weekly allocation of dose 1,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv,71,83,20201221,20210315
7,moderna_allocation_dose2_yyyymmdd,Moderna: weekly allocation of dose 2,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv,84,96,20201221,20210315
8,moderna_receive_dose1_dose2_simultaneously_yyy...,Moderna: receive dose 1 and dose 2 simultaneously,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv,97,109,20201221,20210315
9,moderna_sovereign_nation_supplement_yyyymmdd,Moderna: Sovereign Nation Supplement Project,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv,110,122,20201221,20210315
10,janssen_allocation_dose1_yyyymmdd,Janssen: weekly allocation dose 1,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv,123,124,20210301,20210315
11,janssen_receive_dose1_dose2_simultaneously,Janssen: receive dose 1 and dose 2 simultaneously,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv,125,126,20210301,20210315
12,janssen_sovereign_nation_supplement,Janssen: Sovereign Nation Supplement Project,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv,127,128,20210301,20210315

In [24]:
dictionary = pd.concat([dictionary_casesAndDeaths, dictionary_mobility, dictionary_medical, dictionary_policy, 
                        dictionary_vaccine], sort=False)
dictionary.to_csv("../Pandemic/pandemic_dictionary.csv")

In [25]:
dictionary

,variable name,label,source,file,start column,end column,start date,end date
0,Unnamed: 0,Row number,NaN,casesAndDeaths.csv,0,0,,
1,stfips,State name,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv,1,1,,
2,stname,State FIPS code,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv,2,2,,
3,ctyfips,County name,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv,3,3,,
4,ctyname,County FIPS code,https://www.census.gov/geographies/reference-f...,casesAndDeaths.csv,4,4,,
...,...,...,...,...,...,...,...,...
8,moderna_receive_dose1_dose2_simultaneously_yyy...,Moderna: receive dose 1 and dose 2 simultaneously,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv,97,109,20201221,20210315
9,moderna_sovereign_nation_supplement_yyyymmdd,Moderna: Sovereign Nation Supplement Project,https://covid.cdc.gov/covid-data-tracker/#vacc...,vaccine_allocation.csv,110,122,20201221,20210315
10,janssen_allocation_dose1_yyyymmdd,Janssen: weekly allocation dose 1,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv,123,124,20210301,20210315
11,janssen_receive_dose1_dose2_simultaneously,Janssen: receive dose 1 and dose 2 simultaneously,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv,125,126,20210301,20210315
12,janssen_sovereign_nation_supplement,Janssen: Sovereign Nation Supplement Project,https://data.cdc.gov/Vaccinations/COVID-19-Vac...,vaccine_allocation.csv,127,128,20210301,20210315