# Updated on 05/09/2020

This data contains medical data from the following:
1. Covid tracking project
2. JHU_US_MAP (govex)

In [1]:
import pandas as pd
from datetime import datetime

# Importing the fips data

In [2]:
# importing fips data. and rearranging the columns
fips = pd.read_excel("../Raw data/fips.xlsx")
fips = fips.iloc[:, [1, 3, 2, 4, 5]]

# Convert the 'integers' to integers in fips file.
for i in range(fips.shape[0]):
    if fips.iloc[i, 4] != 'unknown':
        fips.iloc[i, 4] = int(fips.iloc[i, 4])
        fips.iloc[i, 2] = int(fips.iloc[i, 2])

fips = fips.drop(fips[fips.fips == 0].index)
fips = fips.drop(fips[fips.fips == "unknown"].index)
fips = fips.reset_index()
fips = fips.iloc[0:3142, 1:]
fips

      stfips   stname ctyfips            ctyname   fips
0          1  Alabama       1     Autauga County   1001
1          1  Alabama       3     Baldwin County   1003
2          1  Alabama       5     Barbour County   1005
3          1  Alabama       7        Bibb County   1007
4          1  Alabama       9      Blount County   1009
...      ...      ...     ...                ...    ...
3137      56  Wyoming      37  Sweetwater County  56037
3138      56  Wyoming      39       Teton County  56039
3139      56  Wyoming      41       Uinta County  56041
3140      56  Wyoming      43    Washakie County  56043
3141      56  Wyoming      45      Weston County  56045

[3142 rows x 5 columns]

# Govex Medical data (JHU_US_MAP)

In [3]:
df = pd.read_csv("https://opendata.arcgis.com/datasets/4cb598ae041348fb92270f102a6783cb_0.csv")
df.rename(columns={"FIPS":"fips"}, inplace=True)
df = df.iloc[:, 4:]
df

,ST_ID,fips,FatalityRa,Confirmedb,DeathsbyPo,PCTPOVALL_,Unemployme,Med_HH_Inc,State_Fata,DateChecke,...,Age_Less15,Age_15_24,Age_25_34,Age_Over75,Agetotal,NonHisp,Age_35_64,Age_65_74,Shape__Area,Shape__Length
0,1,1001,3.636364,197.84,7.194115,13.8,3.6,118.9591,4.154531,05/17/2020 08:35:53,...,10842,7192,7064,3339,55200,53672,22052,4711,2.209382e+09,246839.865479
1,1,1003,3.149606,116.50,3.669354,9.8,3.6,115.4508,4.154531,05/17/2020 08:35:53,...,37621,23497,23326,16114,208107,198754,82998,24551,5.770469e+09,728445.072448
2,1,1005,1.265823,317.51,4.019131,30.9,5.2,68.9280,4.154531,05/17/2020 08:35:53,...,4517,3092,3675,1814,25782,24676,9864,2820,3.258643e+09,307285.154510
3,1,1007,2.000000,223.21,4.464286,21.8,4.0,92.3478,4.154531,05/17/2020 08:35:53,...,3742,3005,3075,1539,22527,21980,9044,2122,2.310715e+09,227886.963840
4,1,1009,0.000000,77.80,0.000000,13.2,3.5,101.0645,4.154531,05/17/2020 08:35:53,...,11112,6906,6786,4101,57645,52384,22608,6132,2.456058e+09,286306.840721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257,0,90053,0.000000,0.00,0.000000,0.0,0.0,0.0000,0.000000,05/17/2020 08:35:53,...,0,0,0,0,0,0,0,0,NaN,NaN
3258,0,90054,0.000000,0.00,0.000000,0.0,0.0,0.0000,0.000000,05/17/2020 08:35:53,...,0,0,0,0,0,0,0,0,NaN,NaN
3259,0,90055,0.000000,0.00,0.000000,0.0,0.0,0.0000,0.000000,05/17/2020 08:35:53,...,0,0,0,0,0,0,0,0,NaN,NaN
3260,0,90056,NaN,0.00,0.000000,0.0,0.0,0.0000,0.000000,05/17/2020 08:35:53,...,0,0,0,0,0,0,0,0,NaN,NaN
3261,0,99999,2.912621,0.00,0.000000,0.0,0.0,0.0000,0.000000,05/17/2020 08:35:53,...,0,0,0,0,0,0,0,0,NaN,NaN

In [4]:
'''
df = pd.read_csv("../Raw data/JHU_US_MAP.csv")
df.rename(columns={"FIPS":"fips"}, inplace=True)
df = df.iloc[:, 4:]
df
'''

'\ndf = pd.read_csv("../Raw data/JHU_US_MAP.csv")\ndf.rename(columns={"FIPS":"fips"}, inplace=True)\ndf = df.iloc[:, 4:]\ndf\n'

In [5]:
govex_medical = pd.merge(fips, df, on="fips", how="left")
govex_medical

,stfips,stname,ctyfips,ctyname,fips,ST_ID,FatalityRa,Confirmedb,DeathsbyPo,PCTPOVALL_,...,Age_Less15,Age_15_24,Age_25_34,Age_Over75,Agetotal,NonHisp,Age_35_64,Age_65_74,Shape__Area,Shape__Length
0,1,Alabama,1,Autauga County,1001,1,3.636364,197.84,7.194115,13.8,...,10842,7192,7064,3339,55200,53672,22052,4711,2.209382e+09,246839.865479
1,1,Alabama,3,Baldwin County,1003,1,3.149606,116.50,3.669354,9.8,...,37621,23497,23326,16114,208107,198754,82998,24551,5.770469e+09,728445.072448
2,1,Alabama,5,Barbour County,1005,1,1.265823,317.51,4.019131,30.9,...,4517,3092,3675,1814,25782,24676,9864,2820,3.258643e+09,307285.154510
3,1,Alabama,7,Bibb County,1007,1,2.000000,223.21,4.464286,21.8,...,3742,3005,3075,1539,22527,21980,9044,2122,2.310715e+09,227886.963840
4,1,Alabama,9,Blount County,1009,1,0.000000,77.80,0.000000,13.2,...,11112,6906,6786,4101,57645,52384,22608,6132,2.456058e+09,286306.840721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56,Wyoming,37,Sweetwater County,56037,56,0.000000,53.43,0.000000,8.4,...,9911,5873,6551,1660,44117,37075,17061,3061,4.872233e+10,948164.491340
3138,56,Wyoming,39,Teton County,56039,56,0.000000,433.26,0.000000,6.3,...,3868,2027,4239,1048,23059,19626,9790,2087,2.106816e+10,688448.365694
3139,56,Wyoming,41,Uinta County,56041,56,0.000000,49.26,0.000000,10.0,...,5078,2616,2454,893,20609,18725,7963,1605,9.587595e+09,394479.315921
3140,56,Wyoming,43,Washakie County,56043,56,0.000000,114.14,0.000000,11.9,...,1479,988,783,719,8129,6976,3193,967,1.119331e+10,529956.912317
3141,56,Wyoming,45,Weston County,56045,56,0.000000,0.00,0.000000,11.8,...,1287,799,789,625,7100,6993,2885,715,1.194695e+10,437624.020945

# Covid tracking project

In [6]:
df = pd.read_csv("https://covidtracking.com/api/v1/states/daily.csv")
col = [0, 21] + [i for i in range(2, 21)] + [22, 23, 24, 25, 26]
df = df.iloc[:, col]
df.rename(columns={"fips":"stfips"}, inplace=True)
#df

In [7]:
df

,date,stfips,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,death,hospitalized,total,totalTestResults,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200517,2,396.0,34255.0,NaN,13.0,NaN,NaN,NaN,NaN,...,10.0,NaN,34651,34651,34651,0.0,0.0,1366.0,4.0,1370.0
1,20200517,1,11771.0,144579.0,NaN,NaN,1392.0,NaN,504.0,NaN,...,488.0,1392.0,156350,156350,156350,3.0,5.0,2608.0,248.0,2856.0
2,20200517,5,4759.0,80426.0,NaN,65.0,520.0,NaN,NaN,9.0,...,98.0,520.0,85185,85185,85185,0.0,0.0,3360.0,181.0,3541.0
3,20200517,60,0.0,105.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,105,105,105,0.0,0.0,0.0,0.0,0.0
4,20200517,4,13937.0,137824.0,NaN,796.0,1699.0,337.0,NaN,201.0,...,680.0,1699.0,151761,151761,151761,1.0,16.0,4667.0,306.0,4973.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4100,20200126,53,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1,1,1,0.0,0.0,0.0,0.0,0.0
4101,20200125,53,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1,1,1,0.0,0.0,0.0,0.0,0.0
4102,20200124,53,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1,1,1,0.0,0.0,0.0,0.0,0.0
4103,20200123,53,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1,1,1,0.0,0.0,0.0,0.0,0.0
4104,20200122,53,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN

In [8]:
pivot = pd.pivot_table(df, index=["stfips"], columns=["date"], values=df.columns[2:], aggfunc='first', dropna=False)


pivot.columns = [f'{i}_{j}' for i, j in pivot.columns]
pivot.columns = pivot.columns.map(''.join)
pivot = pivot.reset_index()
pivot

,stfips,dataQualityGrade_20200122,dataQualityGrade_20200123,dataQualityGrade_20200124,dataQualityGrade_20200125,dataQualityGrade_20200126,dataQualityGrade_20200127,dataQualityGrade_20200128,dataQualityGrade_20200129,dataQualityGrade_20200130,...,totalTestResultsIncrease_20200508,totalTestResultsIncrease_20200509,totalTestResultsIncrease_20200510,totalTestResultsIncrease_20200511,totalTestResultsIncrease_20200512,totalTestResultsIncrease_20200513,totalTestResultsIncrease_20200514,totalTestResultsIncrease_20200515,totalTestResultsIncrease_20200516,totalTestResultsIncrease_20200517
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4941.0,5380.0,1927.0,2023.0,3774.0,3154.0,5613.0,4078.0,7431.0,2856.0
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1132.0,976.0,915.0,1316.0,1281.0,688.0,1113.0,656.0,863.0,1370.0
2,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4691.0,4685.0,4567.0,6087.0,6378.0,4908.0,6588.0,7663.0,4787.0,4973.0
3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3999.0,1534.0,0.0,3502.0,1414.0,2771.0,2603.0,5711.0,115.0,3541.0
4,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32398.0,37298.0,43094.0,36233.0,41473.0,32222.0,39059.0,29255.0,45220.0,56117.0
5,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3189.0,2236.0,3838.0,8180.0,-133.0,2593.0,3269.0,3511.0,3810.0,3708.0
6,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4367.0,3028.0,6623.0,2316.0,5916.0,4519.0,6619.0,6346.0,8847.0,5852.0
7,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,938.0,1032.0,1743.0,889.0,1363.0,1462.0,2104.0,1421.0,1480.0,1107.0
8,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1259.0,1068.0,1387.0,691.0,789.0,608.0,1341.0,1340.0,1193.0,994.0
9,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20391.0,14390.0,11217.0,22109.0,18547.0,15159.0,14074.0,0.0,21210.0,21745.0
10,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10264.0,7757.0,8223.0,7741.0,10891.0,11725.0,11977.0,15993.0,19195.0,30106.0
11,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1077.0,-356.0,1008.0,413.0,256.0,426.0,516.0,-105.0,2107.0,791.0
12,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,380.0,536.0,336.0,0.0,563.0,423.0,626.0,991.0,943.0,984.0
13,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20671.0,16617.0,13653.0,12441.0,29266.0,17668.0,22678.0,26565.0,23047.0,20295.0
14,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5346.0,5558.0,4343.0,6659.0,3822.0,3573.0,6156.0,5209.0,5910.0,5885.0
15,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3834.0,1215.0,2698.0,3618.0,3496.0,4431.0,3575.0,4272.0,2734.0,3941.0
16,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2886.0,2225.0,2572.0,1604.0,0.0,3519.0,0.0,3964.0,0.0,0.0
17,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2795.0,5046.0,476.0,0.0,17101.0,6610.0,6761.0,3883.0,6456.0,1951.0
18,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1649.0,9741.0,3715.0,4958.0,7182.0,9892.0,9684.0,5601.0,6553.0,5428.0
19,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.0,34.0,28.0,26.0,15.0,38.0,50.0,38.0,45.0,39.0
20,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3587.0,3841.0,3903.0,4849.0,4723.0,4071.0,4880.0,4372.0,7349.0,4751.0
21,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14391.0,10514.0,11852.0,6339.0,6768.0,8536.0,0.0,25647.0,12410.0,12737.0
22,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13191.0,13233.0,12192.0,13270.0,8942.0,370.0,27623.0,21613.0,425.0,39037.0
23,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3849.0,4993.0,4825.0,4693.0,5053.0,1201.0,6717.0,5917.0,8612.0,7304.0
24,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,404.0,288.0,123.0,14283.0,1807.0,2356.0,5278.0,1497.0,1653.0,4650.0
25,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5099.0,177.0,6648.0,74.0,5676.0,2846.0,2968.0,7348.0,4882.0,17704.0
26,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,698.0,384.0,375.0,868.0,463.0,817.0,697.0,869.0,673.0,794.0
27,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2654.0,2564.0,2593.0,670.0,1704.0,1782.0,3616.0,3874.0,2763.0,5662.0
28,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1987.0,2767.0,2698.0,1275.0,3991.0,2597.0,2812.0,2662.0,1518.0,6973.0
29,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1866.0,1626.0,1155.0,1430.0,678.0,1655.0,1959.0,3437.0,64.0,2076.0
30,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6101.0,6447.0,7241.0,113486.0,7127.0,8390.0,10246.0,11276.0,12252.0,12341.0
31,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3348.0,4230.0,3791.0,5445.0,4223.0,3568.0,4722.0,4590.0,4857.0,4126.0
32,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31627.0,32225.0,29230.0,21653.0,20462.0,33794.0,39850.0,39291.0,40669.0,34679.0
33,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7285.0,7749.0,5773.0,3730.0,6379.0,8213.0,8811.0,12279.0,7039.0,10358.0
34,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1634.0,1432.0,936.0,2145.0,818.0,1113.0,1301.0,1469.0,1772.0,1734.0
35,39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8257.0,12354.0,8192.0,5668.0,7201.0,8123.0,7498.0,12830.0,520.0,17760.0
36,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2970.0,6012.0,99.0,24.0,119.0,13016.0,3056.0,6009.0,5207.0,73.0
37,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2235.0,1927.0,887.0,2099.0,0.0,6381.0,63.0,5456.0,2693.0,2157.0
38,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7771.0,6548.0,7276.0,4475.0,7122.0,6889.0,8326.0,8637.0,8004.0,5068.0
39,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2948.0,2549.0,3398.0,2119.0,1907.0,2683.0,3679.0,3377.0,3502.0,4070.0
40,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-4040.0,7521.0,3494.0,0.0,8683.0,0.0,9395.0,7081.0,0.0,10715.0
41,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1179.0,1659.0,942.0,684.0,619.0,647.0,629.0,941.0,762.0,383.0
42,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7250.0,9170.0,9121.0,11408.0,10547.0,9093.0,9400.0,7439.0,10445.0,5079.0
43,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21956.0,12176.0,12482.0,23921.0,12475.0,49259.0,35853.0,22708.0,32479.0,14805.0
44,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4145.0,4606.0,3216.0,4075.0,2900.0,3301.0,3333.0,3099.0,3556.0,3978.0
45,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,557.0,519.0,521.0,823.0,391.0,414.0,829.0,700.0,-929.0,6.0
46,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6793.0,7204.0,5906.0,7562.0,4712.0,6063.0,5438.0,11184.0,7554.0,4793.0
47,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5867.0,5155.0,7154.0,5886.0,3233.0,4213.0,4759.0,6851.0,5372.0,7690.0
48,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1915.0,1561.0,1647.0,825.0,1600.0,1611.0,2033.0,2223.0,2457.0,2097.0
49,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4605.0,5019.0,3508.0,3069.0,4908.0,4654.0,5860.0,6469.0,6051.0,5824.0
50,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,9.0,17.0,1.0,2994.0,0.0,371.0,592.0,372.0,691.0
51,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0
52,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.0,17.0,0.0,195.0,102.0,171.0,117.0,136.0,4.0,85.0
53,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,538.0,1.0,0.0,358.0,178.0,167.0,285.0,0.0,14.0,0.0
54,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,125.0,17.0,25.0,58.0,43.0,30.0,98.0,115.0,47.0,57.0
55,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.0,0.0,79.0,8.0,5.0,13.0,36.0,30.0,0.0,84.0

In [9]:
covidtracking = pd.merge(fips, pivot, on="stfips", how="left")

In [10]:
covidtracking =covidtracking.iloc[:, 5:]
medical = pd.concat([govex_medical, covidtracking], axis=1)
medical.to_csv("../medical.csv")

In [11]:
medical = pd.read_csv("../medical.csv")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [12]:
medical.columns[71]

'dataQualityGrade_20200122'