# Updated on 05/09/2020

This data contains medical data from the following:
1. Covid tracking project
2. JHU_US_MAP (govex)

In [1]:
import pandas as pd
from datetime import datetime

# Importing the fips data

In [2]:
# importing fips data. and rearranging the columns
fips = pd.read_excel("../Raw data/fips.xlsx")
fips = fips.iloc[:, [1, 3, 2, 4, 5]]

# Convert the 'integers' to integers in fips file.
for i in range(fips.shape[0]):
    if fips.iloc[i, 4] != 'unknown':
        fips.iloc[i, 4] = int(fips.iloc[i, 4])
        fips.iloc[i, 2] = int(fips.iloc[i, 2])

fips = fips.drop(fips[fips.fips == 0].index)
fips = fips.drop(fips[fips.fips == "unknown"].index)
fips = fips.reset_index()
fips = fips.iloc[0:3142, 1:]
fips

      stfips   stname ctyfips            ctyname   fips
0          1  Alabama       1     Autauga County   1001
1          1  Alabama       3     Baldwin County   1003
2          1  Alabama       5     Barbour County   1005
3          1  Alabama       7        Bibb County   1007
4          1  Alabama       9      Blount County   1009
...      ...      ...     ...                ...    ...
3137      56  Wyoming      37  Sweetwater County  56037
3138      56  Wyoming      39       Teton County  56039
3139      56  Wyoming      41       Uinta County  56041
3140      56  Wyoming      43    Washakie County  56043
3141      56  Wyoming      45      Weston County  56045

[3142 rows x 5 columns]

# Govex Medical data (JHU_US_MAP)

In [3]:
df = pd.read_csv("https://opendata.arcgis.com/datasets/4cb598ae041348fb92270f102a6783cb_0.csv")
df.rename(columns={"FIPS":"fips"}, inplace=True)
df = df.iloc[:, 4:]
df

,ST_ID,fips,FatalityRa,Confirmedb,DeathsbyPo,PCTPOVALL_,Unemployme,Med_HH_Inc,State_Fata,DateChecke,...,Inpat_Occ,ICU_Occ,Inpat_Cap,Inpat_COV,Inp_nonCOV,ICU_Cap,ICU_COV,ICU_nonCOV,Shape__Area,Shape__Length
0,1,1001,1.452708,11390.08,165.464650,13.8,3.6,118.9591,2.028916,03/06/2021 15:01:23,...,64.119601,90.476190,86.000000,9.142857,46.000000,6.000000,2.000000,3.428571,2.209382e+09,246839.865479
1,1,1003,1.452991,9122.93,132.555430,9.8,3.6,115.4508,2.028916,03/06/2021 15:01:23,...,58.542141,74.107143,439.000000,30.428571,226.571429,32.000000,8.857143,14.857143,5.770469e+09,728445.072448
2,1,1005,2.384292,8596.92,204.975684,30.9,5.2,68.9280,2.028916,03/06/2021 15:01:23,...,50.432277,85.714286,49.571429,2.714286,22.285714,5.000000,1.857143,2.428571,3.258643e+09,307285.154510
3,1,1007,2.360602,10968.75,258.928571,21.8,4.0,92.3478,2.028916,03/06/2021 15:01:23,...,0.000000,NaN,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.310715e+09,227886.963840
4,1,1009,2.049312,10798.76,221.300138,13.2,3.5,101.0645,2.028916,03/06/2021 15:01:23,...,36.309524,0.000000,48.000000,1.428571,16.000000,6.000000,0.000000,0.000000,2.456058e+09,286306.840721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326,0,0,0.000000,0.00,0.000000,0.0,0.0,0.0000,1.716572,03/06/2021 15:01:23,...,15.881737,8.064516,546.000000,6.571429,80.142857,8.857143,0.000000,0.714286,NaN,NaN
3327,0,0,0.000000,0.00,0.000000,0.0,0.0,0.0000,1.388889,03/06/2021 15:01:23,...,15.881737,8.064516,546.000000,6.571429,80.142857,8.857143,0.000000,0.714286,NaN,NaN
3328,0,0,0.000000,0.00,0.000000,0.0,0.0,0.0000,2.034314,03/06/2021 15:01:23,...,15.881737,8.064516,546.000000,6.571429,80.142857,8.857143,0.000000,0.714286,NaN,NaN
3329,0,0,0.000000,0.00,0.000000,0.0,0.0,0.0000,0.000000,03/06/2021 15:01:23,...,15.881737,8.064516,546.000000,6.571429,80.142857,8.857143,0.000000,0.714286,NaN,NaN
3330,0,0,0.000000,0.00,0.000000,0.0,0.0,0.0000,0.921150,03/06/2021 15:01:23,...,15.881737,8.064516,546.000000,6.571429,80.142857,8.857143,0.000000,0.714286,NaN,NaN

In [4]:
'''
df = pd.read_csv("../Raw data/JHU_US_MAP.csv")
df.rename(columns={"FIPS":"fips"}, inplace=True)
df = df.iloc[:, 4:]
df
'''

'\ndf = pd.read_csv("../Raw data/JHU_US_MAP.csv")\ndf.rename(columns={"FIPS":"fips"}, inplace=True)\ndf = df.iloc[:, 4:]\ndf\n'

In [4]:
govex_medical = pd.merge(fips, df, on="fips", how="left")
govex_medical

,stfips,stname,ctyfips,ctyname,fips,ST_ID,FatalityRa,Confirmedb,DeathsbyPo,PCTPOVALL_,...,Inpat_Occ,ICU_Occ,Inpat_Cap,Inpat_COV,Inp_nonCOV,ICU_Cap,ICU_COV,ICU_nonCOV,Shape__Area,Shape__Length
0,1,Alabama,1,Autauga County,1001,1,1.452708,11390.08,165.464650,13.8,...,64.119601,90.476190,86.000000,9.142857,46.000000,6.0,2.000000,3.428571,2.209382e+09,246839.865479
1,1,Alabama,3,Baldwin County,1003,1,1.452991,9122.93,132.555430,9.8,...,58.542141,74.107143,439.000000,30.428571,226.571429,32.0,8.857143,14.857143,5.770469e+09,728445.072448
2,1,Alabama,5,Barbour County,1005,1,2.384292,8596.92,204.975684,30.9,...,50.432277,85.714286,49.571429,2.714286,22.285714,5.0,1.857143,2.428571,3.258643e+09,307285.154510
3,1,Alabama,7,Bibb County,1007,1,2.360602,10968.75,258.928571,21.8,...,0.000000,NaN,34.000000,0.000000,0.000000,0.0,0.000000,0.000000,2.310715e+09,227886.963840
4,1,Alabama,9,Blount County,1009,1,2.049312,10798.76,221.300138,13.2,...,36.309524,0.000000,48.000000,1.428571,16.000000,6.0,0.000000,0.000000,2.456058e+09,286306.840721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56,Wyoming,37,Sweetwater County,56037,56,0.940193,8894.10,83.621751,8.4,...,32.492997,23.809524,51.000000,1.285714,15.285714,9.0,1.285714,0.857143,4.872233e+10,948164.491340
3138,56,Wyoming,39,Teton County,56039,56,0.266667,14622.42,38.993111,6.3,...,32.857143,0.000000,60.000000,1.714286,18.000000,6.0,0.000000,0.000000,2.106816e+10,688448.365694
3139,56,Wyoming,41,Uinta County,56041,56,0.579710,10197.55,59.116213,10.0,...,8.116883,0.000000,44.000000,0.000000,3.571429,3.0,0.000000,0.000000,9.587595e+09,394479.315921
3140,56,Wyoming,43,Washakie County,56043,56,2.931229,11249.21,329.740013,11.9,...,19.841270,0.000000,18.000000,0.000000,3.571429,3.0,0.000000,0.000000,1.119331e+10,529956.912317
3141,56,Wyoming,45,Weston County,56045,56,0.802568,8942.16,71.766901,11.8,...,0.000000,NaN,12.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.194695e+10,437624.020945

In [14]:
df.to_csv('../medical_govex.csv')

# Covid tracking project
According to its official website (https://covidtracking.com/data/api), this Covid tracking project is ending all data collection on March 7, 2021. The existing API will continue to work until May 2021, but will only include data up to March 7, 2021.

In [9]:
df = pd.read_csv("https://covidtracking.com/api/v1/states/daily.csv")
#col = [0, 21] + [i for i in range(2, 21)] + [22, 23, 24, 25, 26]
#df = df.iloc[:, col]
#df.rename(columns={"fips":"stfips"}, inplace=True)
df

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20210305,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,NaN,2,3,7c69ab3363700e0bfc193bc3374d28a89a0d1102,0,0,0,0,0,NaN
1,20210305,AL,498887.0,107518.0,1924758.0,NaN,totalTestsPeopleViral,2316127.0,526.0,45976.0,...,NaN,28,169,5789acffb29d541bdafc68570b05d49d8e08dc97,0,0,0,0,0,NaN
2,20210305,AR,324326.0,68961.0,2472738.0,NaN,totalTestsViral,2728103.0,359.0,14903.0,...,NaN,10,27,a06fef34948008705e4a705542367a074df3e6f8,0,0,0,0,0,NaN
3,20210305,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,NaN,0,0,c085b23f74d0864095c4561f85aac340404b7151,0,0,0,0,0,NaN
4,20210305,AZ,823384.0,55824.0,3050890.0,NaN,totalTestsViral,7827570.0,1043.0,57819.0,...,NaN,84,72,c47acc954d80c7b3b422ee6958a7a24dd2944830,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20663,20200117,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,7cefac6b3681020741ca30f45399a7b22f2e45b4,0,0,0,0,0,NaN
20664,20200116,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,650501e005a5ee86d93c5f32dda56735ea2af967,0,0,0,0,0,NaN
20665,20200115,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,4987e61aad88182abfe641033b597304c2153d4f,0,0,0,0,0,NaN
20666,20200114,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,1881c8a2f0d337b22066b4f05df06eb2259e8d57,0,0,0,0,0,NaN
20667,20200113,WA,NaN,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,12b994ad07c276a5278a2465e081751688739765,0,0,0,0,0,NaN

In [10]:
df.columns

Index(['date', 'state', 'positive', 'probableCases', 'negative', 'pending',
       'totalTestResultsSource', 'totalTestResults', 'hospitalizedCurrently',
       'hospitalizedCumulative', 'inIcuCurrently', 'inIcuCumulative',
       'onVentilatorCurrently', 'onVentilatorCumulative', 'recovered',
       'lastUpdateEt', 'dateModified', 'checkTimeEt', 'death', 'hospitalized',
       'hospitalizedDischarged', 'dateChecked', 'totalTestsViral',
       'positiveTestsViral', 'negativeTestsViral', 'positiveCasesViral',
       'deathConfirmed', 'deathProbable', 'totalTestEncountersViral',
       'totalTestsPeopleViral', 'totalTestsAntibody', 'positiveTestsAntibody',
       'negativeTestsAntibody', 'totalTestsPeopleAntibody',
       'positiveTestsPeopleAntibody', 'negativeTestsPeopleAntibody',
       'totalTestsPeopleAntigen', 'positiveTestsPeopleAntigen',
       'totalTestsAntigen', 'positiveTestsAntigen', 'fips', 'positiveIncrease',
       'negativeIncrease', 'total', 'totalTestResultsIncrease', 'posNeg',
       'dataQualityGrade', 'deathIncrease', 'hospitalizedIncrease', 'hash',
       'commercialScore', 'negativeRegularScore', 'negativeScore',
       'positiveScore', 'score', 'grade'],
      dtype='object')

In [8]:
df.columns

Index(['date', 'dateChecked', 'positive', 'probableCases', 'negative',
       'pending', 'totalTestResultsSource', 'totalTestResults',
       'hospitalizedCurrently', 'hospitalizedCumulative', 'inIcuCurrently',
       'inIcuCumulative', 'onVentilatorCurrently', 'onVentilatorCumulative',
       'recovered', 'lastUpdateEt', 'dateModified', 'checkTimeEt', 'death',
       'hospitalized', 'hospitalizedDischarged', 'totalTestsViral',
       'positiveTestsViral', 'negativeTestsViral', 'positiveCasesViral',
       'deathConfirmed'],
      dtype='object')

In [11]:
pivot = pd.pivot_table(df, index=["state"], columns=["date"], values=df.columns[2:], aggfunc='first', dropna=False)


pivot.columns = [f'{i}_{j}' for i, j in pivot.columns]
pivot.columns = pivot.columns.map(''.join)
pivot = pivot.reset_index()
pivot

,state,checkTimeEt_20200113,checkTimeEt_20200114,checkTimeEt_20200115,checkTimeEt_20200116,checkTimeEt_20200117,checkTimeEt_20200118,checkTimeEt_20200119,checkTimeEt_20200120,checkTimeEt_20200121,...,totalTestsViral_20210224,totalTestsViral_20210225,totalTestsViral_20210226,totalTestsViral_20210227,totalTestsViral_20210228,totalTestsViral_20210301,totalTestsViral_20210302,totalTestsViral_20210303,totalTestsViral_20210304,totalTestsViral_20210305
0,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1662156.0,1671043.0,1679675.0,1679675.0,1679675.0,1698031.0,1704660.0,1711018.0,1724484.0,1731628.0
1,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2618676.0,2627733.0,2634339.0,2641892.0,2695887.0,2698497.0,2702395.0,2709946.0,2719229.0,2728103.0
3,AS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2140.0,2140.0,2140.0,2140.0,2140.0,2140.0,2140.0,2140.0,2140.0,2140.0
4,AZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7512395.0,7549777.0,7596552.0,7623393.0,7663423.0,7682489.0,7701480.0,7739361.0,7775843.0,7827570.0
5,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,47652172.0,47814160.0,47995576.0,48219490.0,48469106.0,48712676.0,48897190.0,49028048.0,49147685.0,49294503.0
6,CO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,CT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6227431.0,6267131.0,6299277.0,6299277.0,6299277.0,6403426.0,6418467.0,6435635.0,6478498.0,6520366.0
8,DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,DE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,FL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18763395.0,18846515.0,18922497.0,18990710.0,19055118.0,19078033.0,19167318.0,19218847.0,19293295.0,19371172.0
11,GA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7096779.0,7125751.0,7153524.0,7181994.0,7201974.0,7215169.0,7234444.0,7251427.0,7279616.0,7315477.0
12,GU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,116684.0,117056.0,117392.0,117392.0,117392.0,117392.0,119080.0,119461.0,119887.0,120426.0
13,HI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,IA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2677457.0,2687335.0,2695742.0,2701416.0,2706509.0,2711184.0,2716525.0,2725336.0,2734777.0,2742341.0
15,ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1066095.0,1070527.0,1075256.0,1080708.0,1083384.0,1083384.0,1088968.0,1092871.0,1096824.0,1100276.0
16,IL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17804537.0,17895829.0,17988085.0,18069753.0,18136253.0,18178487.0,18234668.0,18315522.0,18389512.0,18492848.0
17,IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7856992.0,7902509.0,7942952.0,7989954.0,8021430.0,8035726.0,8056112.0,8093057.0,8133596.0,8171222.0
18,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2438740.0,2438740.0,2468690.0,2468690.0,2468690.0,2485181.0,2485181.0,2504238.0,2504238.0,2525259.0
19,KY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3862877.0,3878912.0,3891701.0,3904567.0,3904567.0,3919142.0,3922153.0,3940366.0,3954639.0,3969899.0
20,LA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5408554.0,5461626.0,5484988.0,5484988.0,5517015.0,5525247.0,5548222.0,5569524.0,5594088.0,5613095.0
21,MA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15776531.0,15894675.0,15997259.0,16105520.0,16208091.0,16261930.0,16317937.0,16419989.0,16522351.0,16628614.0
22,MD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7718790.0,7755974.0,7804095.0,7848245.0,7887028.0,7906291.0,7917331.0,7948627.0,7982350.0,8024078.0
23,ME,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1556092.0,1567428.0,1579975.0,1588504.0,1597098.0,1600443.0,1609150.0,1622215.0,1633308.0,1644587.0
24,MI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10258784.0,10308944.0,10350910.0,10387891.0,10387891.0,10436278.0,10455684.0,10492137.0,10538623.0,10584735.0
25,MN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,MO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4422930.0,4445341.0,4459175.0,4472822.0,4482293.0,4490001.0,4497905.0,4508176.0,4524474.0,4541067.0
27,MP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26131.0,26131.0,26131.0,26131.0,26131.0,26131.0,26131.0,26131.0,26131.0,26131.0
28,MS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1617180.0,1617180.0,1617180.0,1617180.0,1617180.0,1642348.0,1642348.0,1642348.0,1642348.0,1642348.0
29,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1056170.0,1063419.0,1069964.0,1074437.0,1077988.0,1079671.0,1081562.0,1086548.0,1091522.0,1096913.0
30,NC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9310743.0,9361775.0,9422466.0,9463409.0,9499985.0,9525274.0,9541671.0,9561647.0,9605697.0,9650184.0
31,ND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1500838.0,1505995.0,1511734.0,1514345.0,1515035.0,1516683.0,1519660.0,1524029.0,1528837.0,1533007.0
32,NE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2335453.0,2347453.0,2356795.0,2366126.0,2371202.0,2373731.0,2382251.0,2392401.0,2403686.0,2411545.0
33,NH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1419496.0,1436668.0,1436668.0,1451685.0,1458750.0,1461579.0,1465475.0,1467389.0,1474441.0,1481488.0
34,NJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10402049.0,10448986.0,10503667.0,10567646.0,10567646.0,10567646.0,10690625.0,10806397.0,10806397.0,10902830.0
35,NM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2642422.0,2652210.0,2669565.0,2681383.0,2693461.0,2699792.0,2710151.0,2720382.0,2738734.0,2757994.0
36,NV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,OH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9849578.0,9894516.0,9940287.0,9994327.0,10030523.0,10056602.0,10084481.0,10101222.0,10144547.0,10187678.0
39,OK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3418737.0,3429181.0,3474706.0,3471392.0,3471392.0,3483450.0,3499681.0,3516251.0,3527683.0,3536729.0
40,OR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3510691.0,3526219.0,3546317.0,3564120.0,3564120.0,3564120.0,3748444.0,3760400.0,3787438.0,3798067.0
41,PA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,415664.0,415664.0,415664.0,415664.0,415664.0,415664.0,415664.0,415664.0,415664.0,415664.0
43,RI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,SC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4835120.0,4861963.0,4894843.0,4928345.0,4955122.0,4980325.0,4995121.0,5004317.0,5025335.0,5051824.0
45,SD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,685063.0,686758.0,688675.0,690339.0,691692.0,692321.0,692858.0,694883.0,696656.0,698456.0
46,TN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6709400.0,6735104.0,6753759.0,6769438.0,6780861.0,6789970.0,6797475.0,6817121.0,6834882.0,6856581.0
47,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19303921.0,19357913.0,19426513.0,19488683.0,19557682.0,19595211.0,19643058.0,19707655.0,19764177.0,19820052.0
48,UT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2819300.0,2829905.0,2838991.0,2847706.0,2853915.0,2859188.0,2865473.0,2876176.0,2886369.0,2895082.0
49,VA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,VI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,VT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1031951.0,1033554.0,1049205.0,1059706.0,1068299.0,1076259.0,1078840.0,1083198.0,1094855.0,1107296.0
52,WA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,WI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,WV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2135830.0,2147188.0,2157856.0,2166580.0,2177597.0,2181927.0,2190001.0,2198254.0,2207676.0,2218488.0
55,WY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,629838.0,633626.0,636716.0,636716.0,636716.0,640594.0,641380.0,643476.0,646179.0,649293.0

In [15]:
pivot.to_csv('../medical_covidtracking.csv')

# Previous code. Don't run.
The following commands should not be run starting from March 7 2021, because they create duplicate rows for state when merge the state level data into state-county level data

In [9]:
covidtracking = pd.merge(fips, pivot, on="stfips", how="left")

In [10]:
covidtracking =covidtracking.iloc[:, 5:]
medical = pd.concat([govex_medical, covidtracking], axis=1)
medical.to_csv("../medical.csv")

In [11]:
medical = pd.read_csv("../medical.csv")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [12]:
medical.columns[71]

'dataQualityGrade_20200122'