In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [27]:
#Importing the google file from the server
google = pd.read_csv("Global_Mobility_Report.csv")

In [28]:
google.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,2020-02-15,0.0,4.0,5.0,0.0,2.0,1.0
1,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,2020-02-16,1.0,4.0,4.0,1.0,2.0,1.0
2,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,2020-02-17,-1.0,1.0,5.0,1.0,2.0,1.0
3,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,2020-02-18,-2.0,1.0,5.0,0.0,2.0,1.0
4,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,2020-02-19,-2.0,0.0,4.0,-1.0,2.0,1.0

In [29]:
# selecting only the USA
google = google.loc[google["country_region_code"] == "US"]

In [30]:
google = google.reset_index(drop=True)

In [31]:
google.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0

In [32]:
# deleting irrelevant columns
google = google.iloc[:, 2:]

In [33]:
google.head()

,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,NaN,NaN,NaN,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,NaN,NaN,NaN,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,NaN,NaN,NaN,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,NaN,NaN,NaN,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,NaN,NaN,NaN,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0

In [34]:
# Renaming the columns
cols = google.columns
google.rename(columns={cols[0]:"stname", cols[1]:"ctyname",  cols[6]:"retail", cols[7]:"grocery", cols[8]:"parks", cols[9]: "transit", cols[10]: "workplace", cols[11]:"residential"}, inplace=True)
google

,stname,ctyname,metro_area,iso_3166_2_code,census_fips_code,date,retail,grocery,parks,transit,workplace,residential
0,NaN,NaN,NaN,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,NaN,NaN,NaN,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,NaN,NaN,NaN,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,NaN,NaN,NaN,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,NaN,NaN,NaN,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
686737,Wyoming,Weston County,NaN,NaN,56045.0,2020-11-09,NaN,NaN,NaN,NaN,-20.0,NaN
686738,Wyoming,Weston County,NaN,NaN,56045.0,2020-11-10,NaN,NaN,NaN,NaN,-16.0,NaN
686739,Wyoming,Weston County,NaN,NaN,56045.0,2020-11-11,NaN,NaN,NaN,NaN,-27.0,NaN
686740,Wyoming,Weston County,NaN,NaN,56045.0,2020-11-12,NaN,NaN,NaN,NaN,-17.0,NaN
686741,Wyoming,Weston County,NaN,NaN,56045.0,2020-11-13,NaN,NaN,NaN,NaN,-21.0,NaN

In [37]:
#Dropping the columns which have been added since Aditya's script
google.drop(['metro_area','iso_3166_2_code'], axis=1)

,stname,ctyname,census_fips_code,date,retail,grocery,parks,transit,workplace,residential
0,NaN,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,NaN,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,NaN,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,NaN,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,NaN,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
686737,Wyoming,Weston County,56045.0,2020-11-09,NaN,NaN,NaN,NaN,-20.0,NaN
686738,Wyoming,Weston County,56045.0,2020-11-10,NaN,NaN,NaN,NaN,-16.0,NaN
686739,Wyoming,Weston County,56045.0,2020-11-11,NaN,NaN,NaN,NaN,-27.0,NaN
686740,Wyoming,Weston County,56045.0,2020-11-12,NaN,NaN,NaN,NaN,-17.0,NaN
686741,Wyoming,Weston County,56045.0,2020-11-13,NaN,NaN,NaN,NaN,-21.0,NaN

In [42]:
# deleting irrelevant columns
# Reshaping the file.
pivot = pd.pivot_table(google, index=["stname", "ctyname"], columns=["date"], values=google.columns[3:], aggfunc='first')
pivot

                          census_fips_code                                   \
date                            2020-02-15 2020-02-16 2020-02-17 2020-02-18
stname  ctyname
Alabama Autauga County              1001.0     1001.0     1001.0     1001.0
        Baldwin County              1003.0     1003.0     1003.0     1003.0
        Barbour County              1005.0     1005.0     1005.0     1005.0
        Bibb County                 1007.0     1007.0     1007.0     1007.0
        Blount County               1009.0     1009.0     1009.0     1009.0
...                                    ...        ...        ...        ...
Wyoming Sweetwater County          56037.0    56037.0    56037.0    56037.0
        Teton County               56039.0    56039.0    56039.0    56039.0
        Uinta County               56041.0    56041.0    56041.0    56041.0
        Washakie County            56043.0        NaN    56043.0    56043.0
        Weston County                  NaN    56045.0    56045.0    56045.0

                                                                       \
date                      2020-02-19 2020-02-20 2020-02-21 2020-02-22
stname  ctyname
Alabama Autauga County        1001.0     1001.0     1001.0     1001.0
        Baldwin County        1003.0     1003.0     1003.0     1003.0
        Barbour County        1005.0     1005.0     1005.0     1005.0
        Bibb County           1007.0     1007.0     1007.0     1007.0
        Blount County         1009.0     1009.0     1009.0     1009.0
...                              ...        ...        ...        ...
Wyoming Sweetwater County    56037.0    56037.0    56037.0    56037.0
        Teton County         56039.0    56039.0    56039.0    56039.0
        Uinta County         56041.0    56041.0    56041.0    56041.0
        Washakie County      56043.0    56043.0    56043.0    56043.0
        Weston County        56045.0    56045.0    56045.0        NaN

                                                 ...  workplace             \
date                      2020-02-23 2020-02-24  ... 2020-11-04 2020-11-05
stname  ctyname                                  ...
Alabama Autauga County        1001.0     1001.0  ...      -20.0      -18.0
        Baldwin County        1003.0     1003.0  ...      -19.0      -19.0
        Barbour County        1005.0     1005.0  ...      -17.0      -17.0
        Bibb County           1007.0     1007.0  ...      -17.0      -15.0
        Blount County         1009.0     1009.0  ...      -22.0      -20.0
...                              ...        ...  ...        ...        ...
Wyoming Sweetwater County    56037.0    56037.0  ...      -15.0      -13.0
        Teton County         56039.0    56039.0  ...      -36.0      -34.0
        Uinta County         56041.0    56041.0  ...      -13.0      -13.0
        Washakie County          NaN    56043.0  ...      -17.0      -12.0
        Weston County            NaN    56045.0  ...      -22.0      -18.0

                                                                       \
date                      2020-11-06 2020-11-07 2020-11-08 2020-11-09
stname  ctyname
Alabama Autauga County         -19.0       -7.0      -13.0      -16.0
        Baldwin County         -20.0      -12.0      -17.0      -21.0
        Barbour County         -19.0      -21.0      -18.0      -15.0
        Bibb County            -13.0       -4.0      -16.0      -13.0
        Blount County          -23.0      -10.0      -21.0      -25.0
...                              ...        ...        ...        ...
Wyoming Sweetwater County      -10.0       -9.0      -13.0      -15.0
        Teton County           -35.0      -44.0      -45.0      -36.0
        Uinta County            -9.0       -4.0      -13.0      -14.0
        Washakie County        -12.0        NaN        NaN      -19.0
        Weston County          -14.0        NaN        NaN      -20.0


date                      2020-11-10 2020-11-11 2020-11-12 2020-11-13
stname  ctyname
Alabama Autauga County         -19.0      -41.0      -19.0      -20.0
        Baldwin County         -23.0      -34.0      -21.0      -22.0
        Barbour County         -20.0      -34.0      -16.0      -19.0
        Bibb County            -12.0      -28.0      -14.0      -10.0
        Blount County          -22.0      -37.0      -23.0      -25.0
...                              ...        ...        ...        ...
Wyoming Sweetwater County      -16.0      -24.0      -17.0      -11.0
        Teton County           -40.0      -43.0      -36.0      -39.0
        Uinta County           -16.0      -25.0      -14.0       -8.0
        Washakie County        -12.0      -30.0      -15.0      -10.0
        Weston County          -16.0      -27.0      -17.0      -21.0

[2832 rows x 1911 columns]

In [43]:
# Changing the column names as per the rule: variable_yyyymmdd
pivot.columns = [f'{i}_{datetime.strptime(j, "%Y-%m-%d").strftime("%Y%m%d")}' for i, j in pivot.columns]
pivot.columns = pivot.columns.map(''.join)
                 
# Reseting the index to get rid of the multi-level indexing
pivot = pivot.reset_index()
#pivot

In [44]:
pivot

,stname,ctyname,census_fips_code_20200215,census_fips_code_20200216,census_fips_code_20200217,census_fips_code_20200218,census_fips_code_20200219,census_fips_code_20200220,census_fips_code_20200221,census_fips_code_20200222,...,workplace_20201104,workplace_20201105,workplace_20201106,workplace_20201107,workplace_20201108,workplace_20201109,workplace_20201110,workplace_20201111,workplace_20201112,workplace_20201113
0,Alabama,Autauga County,1001.0,1001.0,1001.0,1001.0,1001.0,1001.0,1001.0,1001.0,...,-20.0,-18.0,-19.0,-7.0,-13.0,-16.0,-19.0,-41.0,-19.0,-20.0
1,Alabama,Baldwin County,1003.0,1003.0,1003.0,1003.0,1003.0,1003.0,1003.0,1003.0,...,-19.0,-19.0,-20.0,-12.0,-17.0,-21.0,-23.0,-34.0,-21.0,-22.0
2,Alabama,Barbour County,1005.0,1005.0,1005.0,1005.0,1005.0,1005.0,1005.0,1005.0,...,-17.0,-17.0,-19.0,-21.0,-18.0,-15.0,-20.0,-34.0,-16.0,-19.0
3,Alabama,Bibb County,1007.0,1007.0,1007.0,1007.0,1007.0,1007.0,1007.0,1007.0,...,-17.0,-15.0,-13.0,-4.0,-16.0,-13.0,-12.0,-28.0,-14.0,-10.0
4,Alabama,Blount County,1009.0,1009.0,1009.0,1009.0,1009.0,1009.0,1009.0,1009.0,...,-22.0,-20.0,-23.0,-10.0,-21.0,-25.0,-22.0,-37.0,-23.0,-25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2827,Wyoming,Sweetwater County,56037.0,56037.0,56037.0,56037.0,56037.0,56037.0,56037.0,56037.0,...,-15.0,-13.0,-10.0,-9.0,-13.0,-15.0,-16.0,-24.0,-17.0,-11.0
2828,Wyoming,Teton County,56039.0,56039.0,56039.0,56039.0,56039.0,56039.0,56039.0,56039.0,...,-36.0,-34.0,-35.0,-44.0,-45.0,-36.0,-40.0,-43.0,-36.0,-39.0
2829,Wyoming,Uinta County,56041.0,56041.0,56041.0,56041.0,56041.0,56041.0,56041.0,56041.0,...,-13.0,-13.0,-9.0,-4.0,-13.0,-14.0,-16.0,-25.0,-14.0,-8.0
2830,Wyoming,Washakie County,56043.0,NaN,56043.0,56043.0,56043.0,56043.0,56043.0,56043.0,...,-17.0,-12.0,-12.0,NaN,NaN,-19.0,-12.0,-30.0,-15.0,-10.0
2831,Wyoming,Weston County,NaN,56045.0,56045.0,56045.0,56045.0,56045.0,56045.0,NaN,...,-22.0,-18.0,-14.0,NaN,NaN,-20.0,-16.0,-27.0,-17.0,-21.0

In [45]:
for i in range(pivot.shape[0]):
    if fips.loc[(fips["stname"] == pivot.iloc[i, 0]) & (fips["ctyname"] == pivot.iloc[i, 1])].empty == True:
        for county in fips.loc[fips["stname"] == pivot.iloc[i, 0], "ctyname"]:
            
            
            if pivot.iloc[i, 0] == "District of Columbia":
                pivot.iloc[i, 1] = "District of Columbia"
                
            
            city_county = ["Baltimore", "St. Louis", "Fairfax", "Richmond", "Roanoke"]
            
            if pivot.iloc[i, 1] in city_county:
                pivot.iloc[i, 1] = pivot.iloc[i, 1] + " city"
            
            if pivot.iloc[i, 1] in county:
                pivot.iloc[i, 1] = county
                break
            if pivot.iloc[i, 1] == "La Salle Parish":
                pivot.iloc[i, 1] = "La Salle County"
            if pivot.iloc[i, 1] == "DoÃ±a Ana County":
                pivot.iloc[i, 1] = "Doña Ana County"

In [46]:
fips = pd.read_excel("fips.xlsx")

In [47]:
# Generating a google only final data frame
google_only = pd.merge(fips, pivot, on=["stname", "ctyname"], how="left")
google_only

,stfips,stname,ctyfips,ctyname,fips,census_fips_code_20200215,census_fips_code_20200216,census_fips_code_20200217,census_fips_code_20200218,census_fips_code_20200219,...,workplace_20201104,workplace_20201105,workplace_20201106,workplace_20201107,workplace_20201108,workplace_20201109,workplace_20201110,workplace_20201111,workplace_20201112,workplace_20201113
0,1,Alabama,1,Autauga County,1001,1001.0,1001.0,1001.0,1001.0,1001.0,...,-20.0,-18.0,-19.0,-7.0,-13.0,-16.0,-19.0,-41.0,-19.0,-20.0
1,1,Alabama,3,Baldwin County,1003,1003.0,1003.0,1003.0,1003.0,1003.0,...,-19.0,-19.0,-20.0,-12.0,-17.0,-21.0,-23.0,-34.0,-21.0,-22.0
2,1,Alabama,5,Barbour County,1005,1005.0,1005.0,1005.0,1005.0,1005.0,...,-17.0,-17.0,-19.0,-21.0,-18.0,-15.0,-20.0,-34.0,-16.0,-19.0
3,1,Alabama,7,Bibb County,1007,1007.0,1007.0,1007.0,1007.0,1007.0,...,-17.0,-15.0,-13.0,-4.0,-16.0,-13.0,-12.0,-28.0,-14.0,-10.0
4,1,Alabama,9,Blount County,1009,1009.0,1009.0,1009.0,1009.0,1009.0,...,-22.0,-20.0,-23.0,-10.0,-21.0,-25.0,-22.0,-37.0,-23.0,-25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56,Wyoming,37,Sweetwater County,56037,56037.0,56037.0,56037.0,56037.0,56037.0,...,-15.0,-13.0,-10.0,-9.0,-13.0,-15.0,-16.0,-24.0,-17.0,-11.0
3139,56,Wyoming,39,Teton County,56039,56039.0,56039.0,56039.0,56039.0,56039.0,...,-36.0,-34.0,-35.0,-44.0,-45.0,-36.0,-40.0,-43.0,-36.0,-39.0
3140,56,Wyoming,41,Uinta County,56041,56041.0,56041.0,56041.0,56041.0,56041.0,...,-13.0,-13.0,-9.0,-4.0,-13.0,-14.0,-16.0,-25.0,-14.0,-8.0
3141,56,Wyoming,43,Washakie County,56043,56043.0,NaN,56043.0,56043.0,56043.0,...,-17.0,-12.0,-12.0,NaN,NaN,-19.0,-12.0,-30.0,-15.0,-10.0
3142,56,Wyoming,45,Weston County,56045,NaN,56045.0,56045.0,56045.0,56045.0,...,-22.0,-18.0,-14.0,NaN,NaN,-20.0,-16.0,-27.0,-17.0,-21.0

In [48]:
merged_set = set(google_only.iloc[:, 4].tolist())
pivot_set = set(pivot.iloc[:, 1].tolist())
google_only

,stfips,stname,ctyfips,ctyname,fips,census_fips_code_20200215,census_fips_code_20200216,census_fips_code_20200217,census_fips_code_20200218,census_fips_code_20200219,...,workplace_20201104,workplace_20201105,workplace_20201106,workplace_20201107,workplace_20201108,workplace_20201109,workplace_20201110,workplace_20201111,workplace_20201112,workplace_20201113
0,1,Alabama,1,Autauga County,1001,1001.0,1001.0,1001.0,1001.0,1001.0,...,-20.0,-18.0,-19.0,-7.0,-13.0,-16.0,-19.0,-41.0,-19.0,-20.0
1,1,Alabama,3,Baldwin County,1003,1003.0,1003.0,1003.0,1003.0,1003.0,...,-19.0,-19.0,-20.0,-12.0,-17.0,-21.0,-23.0,-34.0,-21.0,-22.0
2,1,Alabama,5,Barbour County,1005,1005.0,1005.0,1005.0,1005.0,1005.0,...,-17.0,-17.0,-19.0,-21.0,-18.0,-15.0,-20.0,-34.0,-16.0,-19.0
3,1,Alabama,7,Bibb County,1007,1007.0,1007.0,1007.0,1007.0,1007.0,...,-17.0,-15.0,-13.0,-4.0,-16.0,-13.0,-12.0,-28.0,-14.0,-10.0
4,1,Alabama,9,Blount County,1009,1009.0,1009.0,1009.0,1009.0,1009.0,...,-22.0,-20.0,-23.0,-10.0,-21.0,-25.0,-22.0,-37.0,-23.0,-25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56,Wyoming,37,Sweetwater County,56037,56037.0,56037.0,56037.0,56037.0,56037.0,...,-15.0,-13.0,-10.0,-9.0,-13.0,-15.0,-16.0,-24.0,-17.0,-11.0
3139,56,Wyoming,39,Teton County,56039,56039.0,56039.0,56039.0,56039.0,56039.0,...,-36.0,-34.0,-35.0,-44.0,-45.0,-36.0,-40.0,-43.0,-36.0,-39.0
3140,56,Wyoming,41,Uinta County,56041,56041.0,56041.0,56041.0,56041.0,56041.0,...,-13.0,-13.0,-9.0,-4.0,-13.0,-14.0,-16.0,-25.0,-14.0,-8.0
3141,56,Wyoming,43,Washakie County,56043,56043.0,NaN,56043.0,56043.0,56043.0,...,-17.0,-12.0,-12.0,NaN,NaN,-19.0,-12.0,-30.0,-15.0,-10.0
3142,56,Wyoming,45,Weston County,56045,NaN,56045.0,56045.0,56045.0,56045.0,...,-22.0,-18.0,-14.0,NaN,NaN,-20.0,-16.0,-27.0,-17.0,-21.0

In [49]:
merged = (google_only.iloc[:, 3].tolist())
original = (pivot.iloc[:, 1].tolist())
mismatch = list(set(original) - set(merged))
mismatch

['Doña Ana County']

In [50]:
# Importing the descartes lab data
sample = pd.read_csv("https://raw.githubusercontent.com/descarteslabs/DL-COVID-19/master/DL-us-mobility-daterow.csv")

# Removing unnecessary columns
col = [0, 3, 4, 5, 6, 7, 8]
sample = sample.iloc[:, col]
#sample

In [51]:
# Pivot
pivot = pd.pivot_table(sample, index=["admin1", "admin2"], columns=["date"], values=sample.columns[4:], aggfunc='first', dropna=False)

# Changing the name of the variables as per variable_date
pivot.columns = [f'{i}_{datetime.strptime(j, "%Y-%m-%d").strftime("%Y%m%d")}' for i, j in pivot.columns]
pivot.columns = pivot.columns.map(''.join)

# Reseting the index to remove the multi dimension indexing                 
pivot = pivot.reset_index()

# Renameing the columns stname and ctyname
pivot.rename(columns={"admin1":"stname", "admin2":"ctyname"}, inplace=True)

#pivot

In [52]:
# Descartes data only. Standalone
descartes_only = pd.merge(fips, pivot, on=["stname", "ctyname"], how="left")
#descartes_only

In [54]:

descartes_only = descartes_only.iloc[:, 5:]

final = pd.concat([google_only, descartes_only], axis=1, join="inner")
final.to_csv("mobility.csv")

In [55]:
final = pd.read_csv("mobility.csv")
final

,Unnamed: 0,stfips,stname,ctyfips,ctyname,fips,census_fips_code_20200215,census_fips_code_20200216,census_fips_code_20200217,census_fips_code_20200218,...,samples_20201104,samples_20201105,samples_20201106,samples_20201107,samples_20201108,samples_20201109,samples_20201110,samples_20201111,samples_20201112,samples_20201113
0,0,1,Alabama,1,Autauga County,1001,1001.0,1001.0,1001.0,1001.0,...,2671.0,2613.0,2738.0,2631.0,2396.0,2687.0,2751.0,2690.0,2771.0,2840.0
1,1,1,Alabama,3,Baldwin County,1003,1003.0,1003.0,1003.0,1003.0,...,10163.0,9536.0,9751.0,9873.0,9265.0,10310.0,11123.0,10643.0,10844.0,11116.0
2,2,1,Alabama,5,Barbour County,1005,1005.0,1005.0,1005.0,1005.0,...,898.0,849.0,952.0,967.0,919.0,949.0,927.0,907.0,936.0,982.0
3,3,1,Alabama,7,Bibb County,1007,1007.0,1007.0,1007.0,1007.0,...,926.0,984.0,974.0,976.0,857.0,967.0,1015.0,994.0,1000.0,1001.0
4,4,1,Alabama,9,Blount County,1009,1009.0,1009.0,1009.0,1009.0,...,2734.0,2808.0,2813.0,2761.0,2471.0,2777.0,2882.0,2832.0,2860.0,3004.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,3137,56,Wyoming,35,Sublette County,56035,56035.0,NaN,56035.0,56035.0,...,1110.0,1056.0,1082.0,1037.0,1011.0,1047.0,1128.0,1106.0,1249.0,1172.0
3138,3138,56,Wyoming,37,Sweetwater County,56037,56037.0,56037.0,56037.0,56037.0,...,293.0,275.0,295.0,310.0,260.0,271.0,299.0,300.0,327.0,306.0
3139,3139,56,Wyoming,39,Teton County,56039,56039.0,56039.0,56039.0,56039.0,...,589.0,552.0,540.0,541.0,526.0,609.0,556.0,595.0,637.0,626.0
3140,3140,56,Wyoming,41,Uinta County,56041,56041.0,56041.0,56041.0,56041.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3141,3141,56,Wyoming,43,Washakie County,56043,56043.0,NaN,56043.0,56043.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
final.columns[516]

'grocery_20201009'